name: Keep Frontend Alive

on:
  schedule:
    # Runs every 14 minutes between 08:00 and 17:58 UTC to prevent Render from sleeping
    - cron: '*/14 8-17 * * *'
  workflow_dispatch: # Allows manual execution from the Actions tab

jobs:
  ping-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Waking up Frontend App
        continue-on-error: true
        run: |
          echo "Sending ping to Frontend URL..."
          curl -sL https://maio.maioli.dev.br/api/ping > /dev/null
          echo "Ping sent successfully."
